import { motion } from "framer-motion";
import { MessageSquareQuote, Lightbulb, Copy, Check } from "lucide-react";
import { useState } from "react";
import { Button } from "../../components/ui/button";

const questions = [
  {
    id: 1,
    category: "Timeline Inconsistency",
    question: "Mr. Sharma, your email dated March 8th references 'the signed agreement.' Can you explain how you discussed a signed agreement four days before the contract's stated execution date of March 12th?",
    basis: "Conflict #1 — Contract date vs. email timestamp",
    sources: ["Contract_NDA_2024.pdf §2.1", "Email #14, 08-Mar-2023"],
    strategy: "Establish knowledge of pre-dating",
    followUp: "If the witness claims the email refers to a different agreement, ask them to identify which agreement and produce it.",
  },
  {
    id: 2,
    category: "Undisclosed Entity",
    question: "Can you describe the nature of your relationship with Apex Holdings Pvt. Ltd., and explain why this entity received three financial transfers yet was not listed in the contract's party schedule?",
    basis: "Conflict #2 — Undisclosed party involvement",
    sources: ["Financial_Statement_Q3.xlsx Row 142", "Contract Schedule A"],
    strategy: "Reveal hidden corporate relationships",
    followUp: "Request beneficial ownership records for Apex Holdings from MCA database.",
  },
  {
    id: 3,
    category: "Witness Credibility",
    question: "Ms. Mehta, on page 47 of your deposition transcript you stated you had 'no knowledge of any amendment.' How do you reconcile this with your signature appearing on the June 15th amendment document?",
    basis: "Conflict #3 — Conflicting witness statement",
    sources: ["Transcript Page 47", "Amendment_June2023.pdf Page 2"],
    strategy: "Impeach witness credibility",
    followUp: "If the witness claims the signature is forged, request handwriting analysis under S.45 Indian Evidence Act.",
  },
];

const DepositionPage = () => {
  const [copied, setCopied] = useState<number | null>(null);

  const handleCopy = (id: number, text: string) => {
    navigator.clipboard.writeText(text);
    setCopied(id);
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div className="max-w-4xl">
      <div className="mb-6">
        <h2 className="font-display text-2xl font-bold mb-1">Deposition Questions</h2>
        <p className="text-sm text-muted-foreground">Strategic questions generated by LangGraph state machine with long-term memory</p>
      </div>

      <div className="space-y-4">
        {questions.map((q, i) => (
          <motion.div
            key={q.id}
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="rounded-xl border border-border bg-card p-5"
          >
            <div className="flex items-center gap-2 mb-3">
              <span className="text-[10px] uppercase tracking-widest font-bold px-2.5 py-1 rounded-full border border-blue-400/20 bg-blue-400/10 text-blue-400">
                {q.category}
              </span>
              <span className="text-[10px] text-muted-foreground ml-auto">Q{q.id}</span>
            </div>

            <div className="relative group">
              <p className="text-sm leading-relaxed mb-4 text-foreground/90 pr-8">
                "{q.question}"
              </p>
              <Button
                variant="ghost"
                size="icon"
                className="absolute top-0 right-0 h-7 w-7 opacity-0 group-hover:opacity-100 transition-opacity"
                onClick={() => handleCopy(q.id, q.question)}
              >
                {copied === q.id ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              </Button>
            </div>

            <div className="flex items-center gap-2 mb-3">
              <Lightbulb className="w-3 h-3 text-primary flex-shrink-0" />
              <span className="text-[11px] text-primary font-medium">{q.strategy}</span>
            </div>

            <div className="p-3 rounded-lg bg-secondary/30 border border-border/30 mb-3">
              <p className="text-[10px] uppercase tracking-widest text-muted-foreground mb-1">Follow-up</p>
              <p className="text-xs text-foreground/70">{q.followUp}</p>
            </div>

            <div className="flex items-center gap-1.5 text-[10px] text-muted-foreground flex-wrap">
              <span>Based on:</span>
              {q.sources.map((s, j) => (
                <span key={j} className="px-1.5 py-0.5 rounded bg-secondary">{s}</span>
              ))}
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
};

export default DepositionPage;